server:
  port: 8088

spring:
  application:
    name: cosplay
  datasource:
    url: jdbc:mysql://localhost:3306/cosplay_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sunkkk0908
  jpa:
    hibernate:
      ddl-auto: update  # 使用update模式
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        # 指定LOB映射
        jdbc:
          lob:
            non_contextual_creation: true
  #  web:
  #    resources:
  #      static-locations: classpath:/static/, file:./uploads/


  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-ef4675810d594b8f9e34b12c34f5c168
      chat:
        options:
          model: qwen3-max
          temperature: 0.7
          max-tokens: 1024
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
app:
  upload:
    dir: ./uploads
  base:
    url: http://localhost:8088


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.ai: INFO
    ai.cosplay: DEBUG

# Spring AI OpenAI-compatible configuration for Aliyun Bailian DeepSeek

management:
  endpoints:
    web:
      exposure:
        include: health,info

